import photography
def feature():
 return ('''<section class="editorial-feature"><div class="feature-photo">'''
  + photography.photo('/assets/project-2-2.jpg',
      'Custom cabinetry and kitchen island in Gold Coast Build’s Glenview custom home')
  + '''<span>GLENVIEW CUSTOM HOME / INTERIOR DETAIL</span></div><div class="feature-story"><div class="eyebrow">A closer look at our work</div><h2>More than square feet.<br>A way of living.</h2><p>In this Glenview residence, a generous kitchen opens into the family room, while custom cabinetry and quartzite surfaces bring character to the spaces used most.</p><p>A floor-to-ceiling stone fireplace anchors the gathering space. Upstairs, a marble primary bath and walk-in steam shower create a quieter retreat. Each part of the home contributes to the whole.</p><div class="feature-facts"><div><strong>5</strong><span>Bedrooms</span></div><div><strong>4.5</strong><span>Bathrooms</span></div></div><a class="text-link" href="/projects/luxurious-new-home-construction-in-glenview-il/">Explore the residence <span>↗</span></a></div></section>''')
def process():
 steps=[('DISCOVER','Begin with your vision.','Tell us about the property, the opportunity, and what you want to achieve. We start with the way the space needs to function and the priorities behind the project.','Your goals · Property · Priorities'),('DEFINE','Make the important decisions early.','Bring the scope, plans, material preferences, and budget expectations into the same conversation. Identify the questions that need to be resolved before work begins.','Scope · Selections · Budget'),('BUILD','Bring the details together.','Move from individual decisions to coordinated construction. The plans, the sequence of work, and the finished details all serve the same vision.','Coordination · Craftsmanship · Progress'),('COMPLETE','Focus on the final experience.','Review how the finished space comes together—from its overall function to the details you touch and see. A project is about the life or business that follows.','Final details · Review · Next chapter')]
 return '<section class="section"><div class="wrap"><div class="section-head"><div><div class="eyebrow">From first conversation to final detail</div><h2>A thoughtful process.<br>A clearer path forward.</h2></div><p>A construction project carries important decisions. Our approach starts by giving those decisions structure.</p></div><div class="journey">'+''.join(f'<article><div class="journey-index">0{i+1}<span>{k}</span></div><div><h3>{h}</h3><p>{p}</p><small>{s}</small></div></article>' for i,(k,h,p,s) in enumerate(steps))+'</div></div></section>'
def service_detail(commercial=False):
 if commercial:
  title='Built for the demands<br>of doing business.'
  intro='A commercial project has to balance the impression a space makes with the work it needs to support.'
  rows=[('New commercial construction','Create a space around the needs of your business from the outset. Begin with the intended use, site, and project scope, then bring the construction requirements into focus.','New spaces · Business requirements · Construction planning'),('Office & retail build-outs','Shape an interior around your team, customers, and daily operations. Consider the layout, finishes, and practical details that influence how the space performs.','Workplaces · Customer-facing spaces · Interior finishes'),('Commercial remodeling','Rework an existing property to reflect the next stage of your business. Update its appearance, improve the use of space, or plan a more extensive transformation.','Existing properties · Reconfigured interiors · Targeted improvements')]
  note='Start with the operational picture.';detail='Share how the property is used today, how that use may change, and any access or scheduling constraints. Those details help frame a more useful conversation about the scope and sequence of work.'
 else:
  title='For the home you imagine.<br>And the life you lead.'
  intro='From a new address to a new chapter in a familiar home, the best place to begin is with how you want to live.'
  rows=[('Custom home construction','Bring a new home to life with a layout and level of finish that reflect your priorities. Consider how the rooms connect, how natural light moves through the home, and where everyday life happens.','New homes · Living spaces · Interior and exterior finishes'),('Whole-home renovation','Look at an existing home as a complete picture. Reconsider the relationship between rooms, update finishes, and bring greater consistency to the spaces you use most.','Existing homes · Interior transformation · Cohesive finishes'),('Condominium & apartment remodeling','Make an urban home feel more personal and work more intelligently. Start with the possibilities of the existing layout and the practical considerations of working within a larger building.','City residences · Space planning priorities · Building coordination'),('Kitchens, baths & interior updates','Give the most frequently used spaces a more considered finish. Cabinetry, surfaces, fixtures, and material transitions can change both the character and everyday experience of a home.','Kitchens · Bathrooms · Interior details')]
  note='Already have drawings or inspiration?';detail='Bring them to the conversation. Existing plans, photographs, and a short list of priorities help us understand your direction and discuss what comes next. You can also contact us while you are still exploring the possibilities.'
 return '<section class="section capability-section"><div class="wrap"><div class="section-head"><div><div class="eyebrow">Explore the possibilities</div><h2>'+title+'</h2></div><p>'+intro+'</p></div><div class="capability-grid">'+''.join(f'<article><div class="eyebrow">0{i+1}</div><h3>{h}</h3><p>{p}</p><small>{s}</small></article>' for i,(h,p,s) in enumerate(rows))+'</div><div class="planning-note"><h3>'+note+'</h3><p>'+detail+'</p></div></div></section>'
def local():
 return '''<section class="section local-section"><div class="wrap local-grid"><div><div class="eyebrow">Rooted in Chicagoland</div><h2>City perspective.<br>Suburban possibility.</h2></div><div><p class="lead">From a residence above Lake Michigan to a custom home on the North Shore, every setting calls for a different response.</p><p>Our portfolio includes projects in Chicago, Highland Park, Glenview, Norridge, and Downers Grove. Tell us where you are planning to build or renovate, and we can discuss your project in its local context.</p><div class="locations"><span>Chicago</span><span>North Shore</span><span>Western Suburbs</span><span>Surrounding Communities</span></div></div></div></section>'''
FAQ_PAIRS=[('What types of projects can we discuss?','Gold Coast Build handles residential and commercial construction, including new homes, renovations, condominium remodeling, commercial spaces, and build-outs. Share the property and scope you have in mind so we can discuss the right starting point.'),('Do I need complete plans before contacting you?','You can start a conversation at the idea stage or bring an existing set of drawings. Let us know what has already been decided and where you would like help moving the project forward.'),('What should I prepare for the first conversation?','Your project address, a short description of the work, any plans or photographs, your timing preferences, and an initial budget range are useful. If some of these are still open, simply tell us where you are in the process.'),('How are budget and timing discussed?','Both depend on the property, the extent of work, the level of finish, and the project’s specific constraints. The first step is to understand those factors so the discussion is grounded in your actual scope.'),('Which areas do you serve?','Gold Coast Build works across Chicago and the surrounding suburbs. Our project portfolio includes the North Shore and western suburbs. Contact us with your project location to discuss coverage.')]

def faq():
 pairs=FAQ_PAIRS
 return '<section class="section questions"><div class="wrap local-grid"><div><div class="eyebrow">Before we begin</div><h2>A few good<br>questions.</h2><p>Useful answers for the first steps of your project.</p></div><div>'+''.join('<details><summary>'+q+'</summary><p>'+a+'</p></details>' for q,a in pairs)+'</div></div></section>'
def about_detail():
 return '''<section class="section company-statement"><div class="wrap"><div class="eyebrow">Our perspective</div><h2>A building makes an impression.<br><span>The experience makes it personal.</span></h2><div class="statement-columns"><p>At Gold Coast Build, we see a project as more than a set of drawings. It is a home someone has imagined, a property with potential, or a space that will support a business’s next chapter. Understanding that purpose gives the work meaning.</p><p>Our approach brings the overall vision and the individual construction details into the same frame. We believe a well-considered project should feel coherent—from the first impression of the exterior to the rooms, materials, and finishes within.</p></div></div></section>'''
def project_notes(i):
 notes=[ [('An open, light-filled plan','Large windows and an open layout draw the city and lake into the living space, making the most of a 929-square-foot footprint.'),('A more personal interior','Custom cabinetry, stainless steel appliances, and updated bathroom finishes bring a clean, contemporary character to the residence.')], [('Space across three levels','The 3,534-square-foot home combines open living areas with three bedrooms and 3.5 bathrooms, offering room for both gathering and retreat.'),('Details that support daily life','White maple cabinetry and quartz countertops anchor the kitchen. A second-floor laundry, mudroom storage, and heated garage add everyday practicality.')], [('Room to gather','The kitchen connects to a family room with an 11-foot ceiling and a full-height stone fireplace. A butler’s pantry links the formal dining and living areas.'),('A quieter side of the home','A primary suite with a marble bath, walk-in steam shower, and dual closets balances the generous entertaining spaces and finished lower level.')], [('Architectural character','The gabled exterior, contrasting materials, and large windows give this Glenview home a distinct presence.'),('Connected interiors','The project photography reveals bright living spaces and a kitchen organized around an island, with cabinetry and finishes carried consistently through the room.')], [('A sense of arrival','The masonry exterior and arched entry establish the character of the home before the interior unfolds.'),('Everyday gathering spaces','An open kitchen and living area, a central island, and a detailed staircase shape the interior shown in the project gallery.')], [('An individual presence','The exterior combines a covered entrance, layered rooflines, and contrasting siding and masonry.'),('See the home in detail','Explore the photographs for a closer look at the exterior composition, materials, and entry details.')], [('An urban approach to townhome living','A structured façade and generous windows create a distinctive street presence for this Downers Grove project.'),('A connected interior','The photographed kitchen, dining, and living areas share an open arrangement, with wood floors and a central island tying the spaces together.')]]
 return '<div class="project-notes">'+''.join('<article><h3>'+h+'</h3><p>'+p+'</p></article>' for h,p in notes[i])+'</div>'

# Company positioning supported by the existing project portfolio and service scope.
def principles():
 return '''<section class="section confidence"><div class="wrap"><div class="section-head"><div><div class="eyebrow">Why Gold Coast Build</div><h2>The vision to see it.<br>The care to build it.</h2></div><p>Your project deserves a builder who sees the full picture: the property, the possibilities, and the details that will make it yours.</p></div><div class="principle-grid"><article><span>01 / PROVEN IN THE WORK</span><h3>From city residences to custom homes.</h3><p>GCB’s portfolio spans a John Hancock Center renovation, new homes in Highland Park and Glenview, and residences in Norridge and Downers Grove. Different settings. Different scales. The same focus on creating a place with character.</p><a class="text-link" href="/projects/">Explore the GCB portfolio <span>↗</span></a></article><article><span>02 / A COMPLETE PERSPECTIVE</span><h3>Your project, considered as a whole.</h3><p>New construction and remodeling each require decisions that reach beyond a single room or finish. Gold Coast Build brings residential and commercial capabilities together with a perspective that connects your goals to the work ahead.</p><a class="text-link" href="/about/">Meet your construction partner <span>↗</span></a></article><article><span>03 / DISTINCTIVE FINISHES</span><h3>The difference lives in the details.</h3><p>Custom cabinetry, carefully selected surfaces, statement fireplaces, and open living spaces appear throughout GCB’s residential work. These are the elements that turn a completed building into a place you are proud to call your own.</p><a class="text-link" href="/projects/luxurious-new-home-construction-in-glenview-il/">Look closer at the craftsmanship <span>↗</span></a></article></div></div></section>'''

def partnership():
 return '''<section class="section partnership"><div class="wrap"><div class="local-grid"><div><div class="eyebrow">Your vision. Gold Coast Build.</div><h2>A partner for your<br>most important spaces.</h2><p class="partnership-intro">The home you build and the business you grow deserve more than a passing impression. They deserve lasting consideration.</p></div><div class="partner-rows"><article><h3>For homeowners with a vision.</h3><p>You may know exactly what you want—or see potential you have not yet put into words. GCB works with the ambition behind the project, whether that means a new custom home, a comprehensive renovation, or a more personal interior.</p></article><article><h3>For businesses ready for their next chapter.</h3><p>Your surroundings influence how customers experience your business and how your team works. Gold Coast Build’s commercial services encompass new spaces, build-outs, and remodeling, with the intended use of the property at the center of the discussion.</p></article><article><h3>For owners who care about the whole result.</h3><p>A successful space brings appearance and function together. GCB’s approach considers the overall vision alongside the construction details, so that conversations about layout, finishes, and scope serve a shared purpose.</p></article></div></div></div></section>'''

def service_pitch(commercial):
 if commercial:
  kicker='Build your next chapter with GCB';h='A space that represents<br>your business at its best.';p='Your commercial property is part of how people experience your company. Gold Coast Build helps turn the need for a new or improved space into a focused construction conversation—one shaped by your operations, the property, and the impression you want to make.';q='Bring us your business goals, your site, and your plans. Together, we can discuss the work that will move your space forward.'
 else:
  kicker='Make it your home. Build it with GCB.';h='A place you are proud<br>to put your name on.';p='The value of a home is felt in the way it lives: a kitchen that draws everyone together, rooms that feel connected, and finishes that make daily routines more enjoyable. Gold Coast Build brings that perspective to custom homes and renovations across Chicagoland.';q='Explore our completed residences, then tell us what you would like your own home to become. The next project starts with your vision.'
 return f'<section class="section service-pitch"><div class="wrap local-grid"><div><div class="eyebrow">{kicker}</div><h2>{h}</h2></div><div><p class="lead">{p}</p><p>{q}</p><a class="text-link" href="/contact/">Talk to Gold Coast Build <span>↗</span></a></div></div></section>'
